<script src="{{ asset('assets/front/') }}/js/bootstrap.bundle.min.js"></script>
<script src="{{ asset('assets/front/') }}/js/all.min.js"></script>
<script src="{{ asset('assets/front/') }}/js/jquery-1.10.1.min.js"></script>
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="{{ asset('assets/front/') }}/js/owl.carousel.min.js"></script>
<script src="{{ asset('assets/front/') }}/js/plugin.js"></script>
<script src="{{ asset('assets/front/') }}/js/main.js"></script>
<script src="{{ asset('assets/front/') }}/js/dropify.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
